name: Testing

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: Frontend  # Set the correct path to your Frontend directory

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10'  # Adjust to the correct Node.js version

      - name: Install dependencies
        working-directory: Frontend  # Set the working directory for npm commands
        run: npm install

      - name: Run tests
        working-directory: Frontend  # Set the working directory for npm commands
        run: npm test -- testRegex='\.test\.tsx?$'
